#!/usr/bin/env bash
# swap-roles.sh — flip attacker/defender, NetworkPolicy direction, start next scoreboard round
# Usage: ./scripts/swap-roles.sh [--dry-run] [--scoreboard-url URL] [--judge-token TOKEN]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_FILE="${ROUND_STATE_FILE:-$ROOT/artifacts/round-state.env}"
DRY_RUN=0
SCOREBOARD_URL="${SCOREBOARD_URL:-http://127.0.0.1:3020}"
JUDGE_TOKEN="${JUDGE_TOKEN:-judge-token}" # INTENTIONALLY WEAK — training only

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --scoreboard-url) SCOREBOARD_URL="${2:-}"; shift 2 ;;
    --judge-token) JUDGE_TOKEN="${2:-}"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run] [--scoreboard-url URL] [--judge-token TOKEN]"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$(dirname "$STATE_FILE")"

ROLE_A="$(kubectl get ns team-a -o jsonpath='{.metadata.labels.role}' 2>/dev/null || echo defender)"
ROLE_B="$(kubectl get ns team-b -o jsonpath='{.metadata.labels.role}' 2>/dev/null || echo attacker)"
[[ -z "$ROLE_A" ]] && ROLE_A=defender
[[ -z "$ROLE_B" ]] && ROLE_B=attacker

echo "==> Current labels: team-a=$ROLE_A team-b=$ROLE_B"

if [[ "$ROLE_A" == "defender" ]]; then
  NEW_A="attacker"
  NEW_B="defender"
  ATTACKER_TEAM="a"
  DEFENDER_TEAM="b"
else
  NEW_A="defender"
  NEW_B="attacker"
  ATTACKER_TEAM="b"
  DEFENDER_TEAM="a"
fi

echo "==> Swap → team-a=$NEW_A team-b=$NEW_B (attacker=$ATTACKER_TEAM defender=$DEFENDER_TEAM)"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRY-RUN: would label roles, patch NetPols, POST ${SCOREBOARD_URL}/api/round/next"
  exit 0
fi

kubectl label ns team-a "role=${NEW_A}" "team=a" "name=team-a" --overwrite
kubectl label ns team-b "role=${NEW_B}" "team=b" "name=team-b" --overwrite

cat >"$ROOT/deploy/k8s/overlays/round-roles.yaml" <<EOF
# Generated by swap-roles.sh — live match state
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    team: a
    role: ${NEW_A}
    name: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    team: b
    role: ${NEW_B}
    name: team-b
EOF

# Defender: allow ingress from attacker only
kubectl -n "team-${DEFENDER_TEAM}" patch networkpolicy allow-attacker-to-app-http --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/ingress/0/from/0/namespaceSelector/matchLabels/team\",\"value\":\"${ATTACKER_TEAM}\"}]"

# Attacker: no peer ingress on app (disabled selector)
kubectl -n "team-${ATTACKER_TEAM}" patch networkpolicy allow-attacker-to-app-http --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/ingress/0/from/0/namespaceSelector/matchLabels/team\",\"value\":\"disabled\"}]"

# Attacker: egress to defender app
kubectl -n "team-${ATTACKER_TEAM}" patch networkpolicy allow-egress-to-opponent-app --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/egress/0/to/0/namespaceSelector/matchLabels/team\",\"value\":\"${DEFENDER_TEAM}\"}]"

# Defender: egress to opponent disabled
kubectl -n "team-${DEFENDER_TEAM}" patch networkpolicy allow-egress-to-opponent-app --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/egress/0/to/0/namespaceSelector/matchLabels/team\",\"value\":\"disabled\"}]"

ROUND_RESP=""
if command -v curl >/dev/null 2>&1; then
  ROUND_RESP=$(curl -sf -X POST "${SCOREBOARD_URL}/api/round/next" \
    -H "X-Judge-Token: ${JUDGE_TOKEN}" \
    -H "Content-Type: application/json" || true)
fi

if [[ -z "$ROUND_RESP" ]] && kubectl -n platform get svc scoreboard >/dev/null 2>&1; then
  ROUND_RESP=$(kubectl -n platform run "curl-round-$(date +%s)" --rm -i --restart=Never \
    --image=curlimages/curl:8.5.0 -- \
    curl -sf -X POST "http://scoreboard.platform.svc.cluster.local/api/round/next" \
    -H "X-Judge-Token: ${JUDGE_TOKEN}" 2>/dev/null || true)
fi

if [[ -n "$ROUND_RESP" ]]; then
  echo "==> scoreboard: $ROUND_RESP"
else
  echo "WARN: scoreboard /api/round/next unreachable — set SCOREBOARD_URL (e.g. http://127.0.0.1:3020)" >&2
fi

ROUND_N="$(echo "$ROUND_RESP" | sed -n 's/.*"n":[[:space:]]*\([0-9]*\).*/\1/p' | head -1)"
cat >"$STATE_FILE" <<EOF
ROUND=${ROUND_N:-2}
ATTACKER_TEAM=${ATTACKER_TEAM}
DEFENDER_TEAM=${DEFENDER_TEAM}
ROLE_A=${NEW_A}
ROLE_B=${NEW_B}
SWAPPED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "==> Wrote $STATE_FILE"
echo "PASS: roles swapped; attacker=$ATTACKER_TEAM defender=$DEFENDER_TEAM"
echo "Next: ./scripts/reset-round.sh --team a --app app2 && ./scripts/reset-round.sh --team b --app app2"
