#!/usr/bin/env bash
# swap-roles.sh — flip attacker/defender from scoreboard SoT, sync k8s, start next round
# Usage: ./scripts/swap-roles.sh [--dry-run] [--scoreboard-url URL] [--judge-token TOKEN]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_FILE="${ROUND_STATE_FILE:-$ROOT/artifacts/round-state.env}"
DRY_RUN=0
SCOREBOARD_URL="${SCOREBOARD_URL:-http://127.0.0.1:3020}"
JUDGE_TOKEN="${JUDGE_TOKEN:-judge-token}" # INTENTIONALLY WEAK — training only

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --scoreboard-url) SCOREBOARD_URL="${2:-}"; shift 2 ;;
    --judge-token) JUDGE_TOKEN="${2:-}"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run] [--scoreboard-url URL] [--judge-token TOKEN]"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$(dirname "$STATE_FILE")"

json_field() {
  # $1=json $2=key — prefer node (repo toolchain), fallback to python3
  local json="$1" key="$2"
  if command -v node >/dev/null 2>&1; then
    node -e "const o=JSON.parse(process.argv[1]); const v=o[process.argv[2]]; if(v==null||v==='') process.exit(2); process.stdout.write(String(v))" "$json" "$key"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import json,sys; o=json.loads(sys.argv[1]); v=o.get(sys.argv[2]);
assert v is not None and v!=''; print(v)" "$json" "$key"
  else
    echo "$json" | sed -n "s/.*\"${key}\":[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p" | head -1
  fi
}

fetch_get_round() {
  local resp=""
  if command -v curl >/dev/null 2>&1; then
    resp=$(curl -sf "${SCOREBOARD_URL}/api/round" || true)
  fi
  if [[ -z "$resp" ]] && kubectl -n platform get svc scoreboard >/dev/null 2>&1; then
    resp=$(kubectl -n platform run "curl-round-get-$(date +%s)" --rm -i --restart=Never \
      --image=curlimages/curl:8.5.0 -- \
      curl -sf "http://scoreboard.platform.svc.cluster.local/api/round" 2>/dev/null || true)
  fi
  printf '%s' "$resp"
}

post_next_round() {
  local resp=""
  if command -v curl >/dev/null 2>&1; then
    resp=$(curl -sf -X POST "${SCOREBOARD_URL}/api/round/next" \
      -H "X-Judge-Token: ${JUDGE_TOKEN}" \
      -H "Content-Type: application/json" || true)
  fi
  if [[ -z "$resp" ]] && kubectl -n platform get svc scoreboard >/dev/null 2>&1; then
    resp=$(kubectl -n platform run "curl-round-next-$(date +%s)" --rm -i --restart=Never \
      --image=curlimages/curl:8.5.0 -- \
      curl -sf -X POST "http://scoreboard.platform.svc.cluster.local/api/round/next" \
      -H "X-Judge-Token: ${JUDGE_TOKEN}" 2>/dev/null || true)
  fi
  printf '%s' "$resp"
}

# Scoreboard is the role authority — do NOT trust namespace labels for flip direction.
ROUND_CUR="$(fetch_get_round)"
if [[ -z "$ROUND_CUR" ]]; then
  echo "ERROR: cannot read ${SCOREBOARD_URL}/api/round — scoreboard is the role source of truth" >&2
  exit 1
fi

CUR_ATTACKER="$(json_field "$ROUND_CUR" attacker_team)"
CUR_DEFENDER="$(json_field "$ROUND_CUR" defender_team)"
CUR_N="$(json_field "$ROUND_CUR" n || true)"
if [[ -z "$CUR_ATTACKER" || -z "$CUR_DEFENDER" ]]; then
  echo "ERROR: /api/round missing attacker_team/defender_team: $ROUND_CUR" >&2
  exit 1
fi

echo "==> Scoreboard round ${CUR_N:-?} roles: attacker=$CUR_ATTACKER defender=$CUR_DEFENDER"
echo "==> Swap → attacker=$CUR_DEFENDER defender=$CUR_ATTACKER (k8s follows after scoreboard advances)"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRY-RUN: would POST ${SCOREBOARD_URL}/api/round/next then label NetPols from response"
  exit 0
fi

# 1) Advance scoreboard first
ROUND_RESP="$(post_next_round)"
if [[ -z "$ROUND_RESP" ]]; then
  echo "ERROR: POST ${SCOREBOARD_URL}/api/round/next failed — refusing to patch k8s out of sync" >&2
  exit 1
fi
echo "==> scoreboard: $ROUND_RESP"

ATTACKER_TEAM="$(json_field "$ROUND_RESP" attacker_team)"
DEFENDER_TEAM="$(json_field "$ROUND_RESP" defender_team)"
ROUND_N="$(json_field "$ROUND_RESP" n)"
if [[ -z "$ATTACKER_TEAM" || -z "$DEFENDER_TEAM" ]]; then
  echo "ERROR: /api/round/next missing roles: $ROUND_RESP" >&2
  exit 1
fi

# Derive team-a / team-b label roles from new scoreboard roles
if [[ "$DEFENDER_TEAM" == "a" ]]; then
  NEW_A="defender"
  NEW_B="attacker"
else
  NEW_A="attacker"
  NEW_B="defender"
fi

echo "==> Syncing k8s → team-a=$NEW_A team-b=$NEW_B (attacker=$ATTACKER_TEAM defender=$DEFENDER_TEAM)"

# 2) Bring cluster into agreement with scoreboard
kubectl label ns team-a "role=${NEW_A}" "team=a" "name=team-a" --overwrite
kubectl label ns team-b "role=${NEW_B}" "team=b" "name=team-b" --overwrite

cat >"$ROOT/deploy/k8s/overlays/round-roles.yaml" <<EOF
# Generated by swap-roles.sh — live match state (roles from scoreboard)
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    team: a
    role: ${NEW_A}
    name: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    team: b
    role: ${NEW_B}
    name: team-b
EOF

# Defender: allow ingress from attacker only
kubectl -n "team-${DEFENDER_TEAM}" patch networkpolicy allow-attacker-to-app-http --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/ingress/0/from/0/namespaceSelector/matchLabels/team\",\"value\":\"${ATTACKER_TEAM}\"}]"

# Attacker: no peer ingress on app (disabled selector)
kubectl -n "team-${ATTACKER_TEAM}" patch networkpolicy allow-attacker-to-app-http --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/ingress/0/from/0/namespaceSelector/matchLabels/team\",\"value\":\"disabled\"}]"

# Attacker: egress to defender app
kubectl -n "team-${ATTACKER_TEAM}" patch networkpolicy allow-egress-to-opponent-app --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/egress/0/to/0/namespaceSelector/matchLabels/team\",\"value\":\"${DEFENDER_TEAM}\"}]"

# Defender: egress to opponent disabled
kubectl -n "team-${DEFENDER_TEAM}" patch networkpolicy allow-egress-to-opponent-app --type json -p \
  "[{\"op\":\"replace\",\"path\":\"/spec/egress/0/to/0/namespaceSelector/matchLabels/team\",\"value\":\"disabled\"}]"

cat >"$STATE_FILE" <<EOF
ROUND=${ROUND_N}
ATTACKER_TEAM=${ATTACKER_TEAM}
DEFENDER_TEAM=${DEFENDER_TEAM}
ROLE_A=${NEW_A}
ROLE_B=${NEW_B}
SWAPPED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "==> Wrote $STATE_FILE"
echo "PASS: roles swapped; attacker=$ATTACKER_TEAM defender=$DEFENDER_TEAM"
echo "Next: ./scripts/reset-round.sh --team a --app app2 && ./scripts/reset-round.sh --team b --app app2"
